### ISSUE TITLE
cifar10 baselines

### ISSUE THREAD

**Issue by ShuangtongLi** [yasesf93/CrossGradientAggregation#1]
hello, I read your paper and it is a nice work. Thanks for sharing your code. However, it seems that the cifar10 baseline for iid setting is relatively poor, as only about 70% acc obtained, while acc around 90% is supposed to be achieved. Do you mind telling me why there is such a gap? Thanks in advance.

**Comment by yasesf93** [comment]
That's a very good question. 
We have used a 2 layer CNN model for learning CIFAR10. As you could see in the supplementary section, this accuracy rises to 80% when we use VGG11 architecture. Also, the effect of hyperparameters is something that can play a part in this. 
In this paper, we are only interested in comparing the performance of the same model with the same set of hyperparameters in iid and non-iid scenario, not basically reporting the best performance that we could achieve. I assert that if we use better hyperparameters combined with sufficiently complex model architectures, we could enhance the performance for all the algorithms, but the gap between the performance of our algorithm and other algorithms should be there.
